export const categories = [
  { id: 1, title: "Bread" },
  { id: 2, title: "Cake" },
  { id: 3, title: "Coffee" },
  { id: 4, title: "Smoothie" },
];
export const products = [
  {
    id: 1,
    category: "Bread",
    title: "Buttery French Morning Croissant",
    price: 5800,
    image: "/image/1.png",
  },
  {
    id: 2,
    category: "Bread",
    title: "Artisan Crusty Rye Loaf",
    price: 6300,
    image: "/image/2.png",
  },
  {
    id: 3,
    category: "Bread",
    title: "Healthy Sesame Multigrain Loaf",
    price: 5800,
    image: "/image/3.png",
  },
  {
    id: 4,
    category: "Bread",
    title: "Golden Classic Sliced Bread",
    price: 6400,
    image: "/image/4.png",
  },

  {
    id: 5,
    category: "Cake",
    title: "Berry Layered Mousse Cake",
    price: 16000,
    image: "/image/5.png",
  },
  {
    id: 6,
    category: "Cake",
    title: "Red velvet double cheese cake",
    price: 10500,
    image: "/image/6.png",
  },
  {
    id: 7,
    category: "Cake",
    title: "Dark Chocolate Fudge Cake",
    price: 10500,
    image: "/image/7.png",
  },
  {
    id: 8,
    category: "Cake",
    title: "Strawberry Glaze Cheesecake",
    price: 12500,
    image: "/image/8.png",
  },

  {
    id: 9,
    category: "Coffee",
    title: "Creamy Classic Hot Cappuccino",
    price: 8000,
    image: "/image/9.png",
  },
  {
    id: 10,
    category: "Coffee",
    title: "Iced Caramel Latte Bliss",
    price: 9500,
    image: "/image/10.png",
  },
  {
    id: 11,
    category: "Coffee",
    title: "Bold Roast Hot Black Coffee",
    price: 8000,
    image: "/image/11.png",
  },
  {
    id: 12,
    category: "Coffee",
    title: "Whipped Ice Mocha Craze",
    price: 8500,
    image: "/image/12.png",
  },

  {
    id: 13,
    category: "Smoothie",
    title: "Frosted Berry Smoothie Burst",
    price: 7800,
    image: "/image/13.png",
  },
  {
    id: 14,
    category: "Smoothie",
    title: "Frosted Strawberry Smoothie Burst",
    price: 7800,
    image: "/image/14.png",
  },
  {
    id: 15,
    category: "Smoothie",
    title: "Frosted Lychee Smoothie Burst",
    price: 9500,
    image: "/image/15.png",
  },
  {
    id: 16,
    category: "Smoothie",
    title: "Frosted Sunkist Smoothie Burst",
    price: 9200,
    image: "/image/16.png",
  },
  {
    id: 17,
    category: "Smoothie",
    title: "Tropical Layered Fruit Smoothie",
    price: 8500,
    image: "/image/17.png",
  },
];
